### ISSUE TITLE
RFE - test/document usage with MAG

### ISSUE THREAD

**Issue by jduncan-rva** [Azure/open-service-broker-azure#495] opened 2018-06-23 19:44 UTC
Test and document any changes needed for the service broker to function properly in MAG.

**Comment by krancour** [comment] 2018-06-24 05:17
MAG?

**Comment by jduncan-rva** [comment] 2018-06-24 17:43
Microsoft Azure for Government. Sorry. Didn't know the acronym wasn't common. Different API endpoints, etc.

**Comment by krancour** [comment] 2018-06-24 20:13
It's actually not supported at all, yet...

This may be a duplicate of #250. I think #250 was probably requested for the sake of the China cloud, but the effort that would probably take care of US gov cloud as well.

**Comment by krancour** [comment] 2018-08-02 04:49
I'm going to close this only because it does seem to be a dup of #250.

**Closed by krancour** 2018-08-02 04:49 UTC
